package extensionsskins

import (
	"fmt"
	"strings"

	"github.com/CanastaWiki/Canasta-CLI/internal/config"
	"github.com/CanastaWiki/Canasta-CLI/internal/orchestrators"
)

type Item struct {
	Name                     string // e.g. "Canasta extension" or "Canasta skin"
	CmdName                  string // e.g. "extension" or "skin"
	Plural                   string // e.g. "extensions" or "skins"
	RelativeInstallationPath string // e.g. "extensions" or "skins"
	PhpCommand               string // e.g. "wfLoadExtension" or "wfLoadSkin"
	ExampleNames             string // e.g. "VisualEditor,Cite,ParserFunctions" or "Timeless"
}

func Contains(list []string, element string) bool {
	for _, item := range list {
		if item == element {
			return true
		}
	}
	return false
}

func List(instance config.Installation, orch orchestrators.Orchestrator, constants Item) error {
	fmt.Printf("Available %s:\n", constants.Name)
	output, err := orch.ExecWithError(instance.Path, orchestrators.ServiceWeb, "cd $MW_HOME/"+constants.RelativeInstallationPath+" && find -L * -maxdepth 0 -type d")
	if err != nil {
		return fmt.Errorf("failed to list %s: %s", constants.Name, output)
	}
	fmt.Print(output)
	return nil
}

func CheckInstalled(name string, instance config.Installation, orch orchestrators.Orchestrator, constants Item) (string, error) {
	output, err := orch.ExecWithError(instance.Path, orchestrators.ServiceWeb, "cd $MW_HOME/"+constants.RelativeInstallationPath+" && find -L * -maxdepth 0 -type d")
	if err != nil {
		return "", fmt.Errorf("failed to check installed %s: %s", constants.Name, output)
	}
	if !Contains(strings.Split(output, "\n"), name) {
		return "", fmt.Errorf("%s %s doesn't exist", constants.Name, name)
	}
	return name, nil
}

func Enable(name, wiki string, instance config.Installation, orch orchestrators.Orchestrator, constants Item) error {
	if wiki == "" {
		fmt.Println("You didn't specify a wiki. The extension or skin will affect all wikis in the corresponding Canasta instance.")
	}

	var filePath string

	if wiki != "" {
		filePath = fmt.Sprintf("/mediawiki/config/settings/wikis/%s/%s.php", wiki, name)
	} else {
		filePath = fmt.Sprintf("/mediawiki/config/settings/global/%s.php", name)
	}

	phpScript := fmt.Sprintf("<?php\n// This file was generated by Canasta\n%s( '%s' );", constants.PhpCommand, name)

	output, err := orch.ExecWithError(instance.Path, orchestrators.ServiceWeb, "ls "+filePath)

	if err == nil {
		fmt.Printf("%s %s is already enabled!\n", constants.Name, name)
	} else if Contains(strings.Split(output, ":"), " No such file or directory\n") {
		command := fmt.Sprintf(`echo -e "%s" > %s`, phpScript, filePath)
		execOutput, execErr := orch.ExecWithError(instance.Path, orchestrators.ServiceWeb, command)
		if execErr != nil {
			return fmt.Errorf("failed to enable %s %q for wiki %q: %s", constants.Name, name, wiki, execOutput)
		}
		fmt.Printf("%s %s enabled\n", constants.Name, name)
	}
	return nil
}

func CheckEnabled(name, wiki string, instance config.Installation, orch orchestrators.Orchestrator, constants Item) (string, error) {
	var settingsPath string
	var filePath string

	if wiki != "" {
		settingsPath = fmt.Sprintf("/mediawiki/config/settings/wikis/%s/", wiki)
		filePath = fmt.Sprintf("/mediawiki/config/settings/wikis/%s/%s.php", wiki, name)
	} else {
		settingsPath = "/mediawiki/config/settings/global/"
		filePath = fmt.Sprintf("/mediawiki/config/settings/global/%s.php", name)
	}

	output, err := orch.ExecWithError(instance.Path, orchestrators.ServiceWeb, "ls "+settingsPath)
	if err != nil {
		return "", fmt.Errorf("failed to check if %s %q is enabled: %s", constants.Name, name, output)
	}
	if !Contains(strings.Split(output, "\n"), name+".php") {
		return "", fmt.Errorf("%s %s is not enabled", constants.Name, name)
	}

	output, err = orch.ExecWithError(instance.Path, orchestrators.ServiceWeb, fmt.Sprintf(`cat %s`, filePath))
	if err != nil {
		return "", fmt.Errorf("failed to read settings for %s %q: %s", constants.Name, name, output)
	}
	if !Contains(strings.Split(output, "\n"), "// This file was generated by Canasta") {
		return "", fmt.Errorf("%s %s was not generated by Canasta cli", constants.Name, name)
	}

	return name, nil
}

func Disable(name, wiki string, instance config.Installation, orch orchestrators.Orchestrator, constants Item) error {
	if wiki == "" {
		fmt.Println("You didn't specify a wiki. The common settings will disable the extension or skin in the corresponding Canasta instance.")
	}

	var filePath string

	if wiki != "" {
		filePath = fmt.Sprintf("/mediawiki/config/settings/wikis/%s/%s.php", wiki, name)
	} else {
		filePath = fmt.Sprintf("/mediawiki/config/settings/global/%s.php", name)
	}

	command := fmt.Sprintf(`rm %s`, filePath)
	output, err := orch.ExecWithError(instance.Path, orchestrators.ServiceWeb, command)
	if err != nil {
		return fmt.Errorf("failed to disable %s %q for wiki %q: %s", constants.Name, name, wiki, output)
	}
	fmt.Printf("%s %s disabled\n", constants.Name, name)
	return nil
}
