package config

import (
	"log"
	"os"

	"github.com/spf13/cobra"

	"github.com/CanastaWiki/Canasta-CLI/internal/canasta"
	"github.com/CanastaWiki/Canasta-CLI/internal/config"
	"github.com/CanastaWiki/Canasta-CLI/internal/logging"
	"github.com/CanastaWiki/Canasta-CLI/internal/orchestrators"
)

var (
	instance config.Installation
	orch     orchestrators.Orchestrator
	verbose  bool
	err      error
)

func NewCmdCreate() *cobra.Command {
	workingDir, wdErr := os.Getwd()
	if wdErr != nil {
		log.Fatal(wdErr)
	}
	instance.Path = workingDir

	configCmd := &cobra.Command{
		Use:   "config",
		Short: "View and modify Canasta configuration",
		Long: `View and modify the .env configuration for a Canasta installation.

Use "canasta config get" to view current settings and "canasta config set"
to change them. The set command handles side effects automatically (e.g.,
updating wikis.yaml when changing HTTPS_PORT) and restarts the instance.
Editing .env by hand may leave the installation in an inconsistent state.

Key names are case-insensitive and hyphens are treated as underscores,
so "https-port", "HTTPS_PORT", and "Https_Port" all work.

Settings safe to change on a running installation:

  Network
    HTTP_PORT                       HTTP port (default: 80)
    HTTPS_PORT                      HTTPS port (default: 443)

  PHP
    PHP_UPLOAD_MAX_FILESIZE         Upload file size limit (default: 10M)
    PHP_POST_MAX_SIZE               POST data size limit (default: 10M)
    PHP_MAX_INPUT_VARS              Max input variables (default: 1000)

  Features
    CANASTA_ENABLE_ELASTICSEARCH    Enable Elasticsearch (default: false)
    CANASTA_ENABLE_OBSERVABILITY    Enable observability stack (default: false)

  Caddy / TLS
    CADDY_AUTO_HTTPS                Set to "off" behind a reverse proxy

  Docker Image
    CANASTA_IMAGE                   Override the default Canasta image

  Backup (Restic)
    RESTIC_REPOSITORY               Restic repo URL or local path
    RESTIC_PASSWORD                 Restic repo password
    AWS_ACCESS_KEY_ID               AWS key for S3 backups
    AWS_SECRET_ACCESS_KEY           AWS secret for S3 backups

Other settings (database passwords, secret keys, MW_SITE_SERVER, etc.)
are generated by "canasta create" and should not be changed directly.
To change the domain, edit config/wikis.yaml instead.`,
		PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
			logging.SetVerbose(verbose)
			instance, err = canasta.CheckCanastaId(instance)
			if err != nil {
				return err
			}
			orch, err = orchestrators.NewFromInstance(instance)
			return err
		},
	}

	configCmd.PersistentFlags().StringVarP(&instance.Id, "id", "i", "", "Canasta instance ID")
	configCmd.PersistentFlags().BoolVarP(&verbose, "verbose", "v", false, "Verbose output")

	configCmd.AddCommand(getCmdCreate())
	configCmd.AddCommand(setCmdCreate())

	return configCmd
}
