---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"

    node1:
      ansible_host: acknowledge.wiki
      ansible_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3

    node2:
      ansible_host: worker.acknowledge.wiki
      ansible_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3
