---
- name: Resolve instance
  ansible.builtin.include_tasks: >-
    {{ canasta_root }}/roles/common/tasks/resolve_instance.yml

- name: Compare snapshots
  ansible.builtin.include_tasks: >-
    {{ canasta_root }}/roles/orchestrator/tasks/run_backup.yml
  vars:
    backup_args:
      - "diff"
      - "{{ snapshot }}"
      - "{{ snapshot2 }}"

- name: Display diff
  ansible.builtin.debug:
    msg: "{{ _restic_result.stdout }}"
