---
- name: Resolve instance
  ansible.builtin.include_tasks: >-
    {{ canasta_root }}/roles/common/tasks/resolve_instance.yml

- name: List files in snapshot
  ansible.builtin.include_tasks: >-
    {{ canasta_root }}/roles/orchestrator/tasks/run_backup.yml
  vars:
    backup_args: ["ls", "{{ snapshot }}"]

- name: Display files
  ansible.builtin.debug:
    msg: "{{ _restic_result.stdout }}"
