---
- name: Resolve instance
  ansible.builtin.include_tasks: "{{ canasta_root }}/roles/common/tasks/resolve_instance.yml"

- name: List backup snapshots
  ansible.builtin.include_role:
    name: orchestrator
    tasks_from: exec.yml
  vars:
    exec_service: "{{ canasta_backup_service }}"
    exec_command: "restic snapshots"

- name: Display snapshots
  ansible.builtin.debug:
    msg: "{{ exec_result.stdout }}"
