---
- name: Resolve instance
  ansible.builtin.include_tasks: >-
    {{ canasta_root }}/roles/common/tasks/resolve_instance.yml

- name: List backup snapshots
  ansible.builtin.include_tasks: >-
    {{ canasta_root }}/roles/orchestrator/tasks/run_backup.yml
  vars:
    backup_args: ["snapshots"]

- name: Display snapshots
  ansible.builtin.debug:
    msg: "{{ _restic_result.stdout }}"
