---
- name: Resolve instance
  ansible.builtin.include_tasks: >-
    {{ canasta_root }}/roles/common/tasks/resolve_instance.yml

- name: Build purge arguments
  ansible.builtin.set_fact:
    _purge_list:
      - "forget"
      - "--prune"

- name: Add keep-last
  ansible.builtin.set_fact:
    _purge_list: >-
      {{ _purge_list + ['--keep-last', keep_last] }}
  when: keep_last is defined and keep_last != ''

- name: Add keep-hourly
  ansible.builtin.set_fact:
    _purge_list: >-
      {{ _purge_list + ['--keep-hourly', keep_hourly] }}
  when: keep_hourly is defined and keep_hourly != ''

- name: Add keep-daily
  ansible.builtin.set_fact:
    _purge_list: >-
      {{ _purge_list + ['--keep-daily', keep_daily] }}
  when: keep_daily is defined and keep_daily != ''

- name: Add keep-monthly
  ansible.builtin.set_fact:
    _purge_list: >-
      {{ _purge_list + ['--keep-monthly', keep_monthly] }}
  when: keep_monthly is defined and keep_monthly != ''

- name: Add keep-within
  ansible.builtin.set_fact:
    _purge_list: >-
      {{ _purge_list + ['--keep-within', older_than] }}
  when: older_than is defined and older_than != ''

- name: Purge old backups
  ansible.builtin.include_tasks: >-
    {{ canasta_root }}/roles/orchestrator/tasks/run_backup.yml
  vars:
    backup_args: "{{ _purge_list }}"

- name: Display result
  ansible.builtin.debug:
    msg: "{{ _restic_result.stdout }}"
