# -*- coding: utf-8 -*-
"""Render an instance's sidecars (config/sidecars.yaml) to runtime artifacts.

Pure functions shared by the canasta_render_sidecars module and its unit
tests. One declaration renders to either a Docker Compose override layer
(`docker-compose.sidecars.yml`) or Helm values (`values-sidecars.yaml`).

`${VAR:-default}` interpolation: Compose interpolates these itself from the
instance `.env`, so the Compose render passes them through unchanged. k8s
has no interpolation, so the k8s render resolves them at render time against
the same `.env`, keeping the value identical on both orchestrators.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

import re

_ENV_REF = re.compile(r"\$\{([A-Za-z_]\w*)(:-|-)?([^}]*)\}")


def resolve_env_value(value, env):
    """Resolve ${VAR}, ${VAR:-default}, ${VAR-default} against an env dict."""
    if not isinstance(value, str):
        return value

    def repl(match):
        name, op, default = match.group(1), match.group(2), match.group(3)
        val = env.get(name)
        if op == ":-":          # unset OR empty -> default
            return val if val else default
        if op == "-":           # unset -> default (empty kept)
            return val if val is not None else default
        return val if val is not None else ""

    return _ENV_REF.sub(repl, value)


# --- Web <-> sidecar env bridge -------------------------------------------- #

# Web pod env is a curated allowlist on both orchestrators, so an instance
# .env var a sidecar references (e.g. a shared secret) does NOT reach the web
# tier's getenv() on its own. This fragment, synced via config/settings/global,
# putenv()s those vars so MediaWiki Settings.php reads the same value the
# sidecar receives — "define once in .env, deliver to both". A sidecar can opt
# a key out via `envPrivate` (delivered to the sidecar, kept out of the web
# tier) — for a secret only the sidecar should hold.
_BRIDGE_HEADER = (
    "<?php\n"
    "// Generated by canasta from config/sidecars.yaml — do not edit.\n"
    "// Bridges instance .env vars referenced by sidecars into the web tier's\n"
    "// getenv(), so Settings.php reads the same values the sidecars receive.\n"
    "// WARNING: values are written in cleartext; on k8s this file lives in the\n"
    "// gitops repo. Use a real secret store for highly sensitive values.\n"
)


def collect_env_refs(sidecars):
    """Instance .env var names referenced by any sidecar's env values or
    command, EXCEPT vars referenced only by env entries the sidecar lists in
    `envPrivate` (delivered to that sidecar but deliberately kept out of the
    web tier's getenv()). A var referenced by any non-private entry anywhere
    is still bridged. `command` refs are always public — secrets belong in env."""
    names = set()
    for sidecar in sidecars or []:
        private = set(sidecar.get("envPrivate") or [])
        values = [v for k, v in (sidecar.get("env") or {}).items()
                  if k not in private]
        command = sidecar.get("command")
        if command:
            values += command if isinstance(command, list) else [command]
        for value in values:
            if isinstance(value, str):
                for match in _ENV_REF.finditer(value):
                    names.add(match.group(1))
    return sorted(names)


def _php_single_quote(value):
    return value.replace("\\", "\\\\").replace("'", "\\'")


def render_env_bridge(sidecars, env):
    """PHP fragment that putenv()s the .env vars a sidecar references, or None
    when no referenced var is present in the instance .env (nothing to bridge)."""
    lines = []
    for name in collect_env_refs(sidecars):
        if name in env:
            lines.append("putenv('%s=%s');"
                         % (name, _php_single_quote(env[name])))
    if not lines:
        return None
    return _BRIDGE_HEADER + "\n".join(lines) + "\n"


# --- Docker Compose -------------------------------------------------------- #

_MEM_UNITS = {
    "Ki": 1024, "Mi": 1024 ** 2, "Gi": 1024 ** 3, "Ti": 1024 ** 4,
    "k": 1000, "K": 1000, "M": 1000 ** 2, "G": 1000 ** 3, "T": 1000 ** 4,
}


def k8s_memory_to_bytes(value):
    """Convert a Kubernetes memory quantity ('256Mi', '1Gi', '512M') to an
    integer byte count, which Docker Compose accepts verbatim — Compose rejects
    the k8s 'Mi'/'Gi' suffixes. A bare number is bytes; an unrecognized value
    is returned unchanged. (The k8s render keeps the original notation.)"""
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return int(value)
    text = str(value).strip()
    if text.isdigit():
        return int(text)
    # Two-char binary suffixes (Mi) before single-char decimal (M).
    for suffix in ("Ki", "Mi", "Gi", "Ti", "K", "M", "G", "T", "k"):
        if text.endswith(suffix):
            try:
                return int(float(text[:-len(suffix)]) * _MEM_UNITS[suffix])
            except ValueError:
                return value
    return value


def _compose_healthcheck(healthcheck):
    if healthcheck.get("command"):
        test = ["CMD"] + list(healthcheck["command"])
    elif healthcheck.get("tcp"):
        test = ["CMD-SHELL", "nc -z localhost %s || exit 1" % healthcheck["tcp"]]
    elif healthcheck.get("path"):
        port = healthcheck.get("port", 80)
        test = ["CMD", "curl", "-f",
                "http://localhost:%s%s" % (port, healthcheck["path"])]
    else:  # bare port -> TCP
        test = ["CMD-SHELL",
                "nc -z localhost %s || exit 1" % healthcheck.get("port")]
    return {"test": test, "interval": "30s", "timeout": "5s", "retries": 3}


def render_compose_service(sidecar):
    """One sidecar -> (compose service dict, {named_volume: None})."""
    service = {}
    if sidecar.get("build"):
        service["build"] = sidecar["build"]
    else:
        service["image"] = sidecar["image"]
    if sidecar.get("command"):
        # Compose accepts a string or list and interpolates ${VAR} itself.
        service["command"] = sidecar["command"]
    service["restart"] = "unless-stopped"
    if sidecar.get("env"):
        service["environment"] = dict(sidecar["env"])
    if sidecar.get("ports"):
        service["expose"] = [str(p) for p in sidecar["ports"]]
    named_volumes = {}
    mounts = []
    for volume in sidecar.get("volumes", []) or []:
        if volume.get("persistent"):
            vol = "%s-%s" % (sidecar["name"], volume["name"])
            mounts.append("%s:%s" % (vol, volume["mountPath"]))
            named_volumes[vol] = None
        else:
            mounts.append(volume["mountPath"])  # anonymous ephemeral
    for fileref in sidecar.get("files", []) or []:
        suffix = ":ro" if fileref.get("readOnly", True) else ""
        mounts.append("./%s:%s%s"
                      % (fileref["source"], fileref["mountPath"], suffix))
    if mounts:
        service["volumes"] = mounts
    if sidecar.get("depends_on"):
        service["depends_on"] = list(sidecar["depends_on"])
    if sidecar.get("healthcheck"):
        service["healthcheck"] = _compose_healthcheck(sidecar["healthcheck"])
    if sidecar.get("resources"):
        limits = {}
        if sidecar["resources"].get("memory"):
            # Compose wants memory as a string byte count (it rejects both the
            # k8s 'Mi'/'Gi' suffix and a bare integer).
            limits["memory"] = str(k8s_memory_to_bytes(
                sidecar["resources"]["memory"]))
        if sidecar["resources"].get("cpu"):
            limits["cpus"] = str(sidecar["resources"]["cpu"])
        if limits:
            service["deploy"] = {"resources": {"limits": limits}}
    return service, named_volumes


def render_compose(sidecars):
    """Sidecars -> a docker-compose override dict, or None when there are none."""
    if not sidecars:
        return None
    services = {}
    volumes = {}
    for sidecar in sidecars:
        service, named = render_compose_service(sidecar)
        services[sidecar["name"]] = service
        volumes.update(named)
    override = {"services": services}
    if volumes:
        override["volumes"] = volumes
    return override


# --- Kubernetes ------------------------------------------------------------ #

def render_k8s_values(sidecars, env, file_reader):
    """Sidecars -> the list for `.Values.sidecars` (env resolved, file
    contents inlined for ConfigMaps). `file_reader(source)` returns the text
    of an instance file. Returns [] when there are no sidecars."""
    out = []
    for sidecar in sidecars or []:
        item = {"name": sidecar["name"]}
        if sidecar.get("build"):
            item["build"] = sidecar["build"]
        else:
            item["image"] = sidecar["image"]
        if sidecar.get("command"):
            item["command"] = resolve_env_value(sidecar["command"], env)
        # envSecret keys are sourced from the per-instance app Secret (rendered
        # as secretKeyRef by the chart), so they are NOT resolved to cleartext
        # here. Everything else stays a resolved literal, exactly as before.
        secret_keys = set(sidecar.get("envSecret") or [])
        if sidecar.get("env"):
            plain = {k: resolve_env_value(v, env)
                     for k, v in sidecar["env"].items() if k not in secret_keys}
            if plain:
                item["env"] = plain
        if secret_keys:
            item["envSecret"] = sorted(secret_keys)
        if sidecar.get("ports"):
            item["ports"] = [int(p) for p in sidecar["ports"]]
        if sidecar.get("volumes"):
            item["volumes"] = sidecar["volumes"]
        if sidecar.get("files"):
            item["files"] = [
                {"mountPath": fileref["mountPath"],
                 "readOnly": fileref.get("readOnly", True),
                 "content": file_reader(fileref["source"])}
                for fileref in sidecar["files"]
            ]
        if sidecar.get("depends_on"):
            item["depends_on"] = list(sidecar["depends_on"])
        if sidecar.get("healthcheck"):
            item["healthcheck"] = sidecar["healthcheck"]
        if sidecar.get("resources"):
            item["resources"] = sidecar["resources"]
        out.append(item)
    return out
