---
- name: Resolve instance
  ansible.builtin.include_tasks: "{{ playbook_dir }}/roles/common/tasks/resolve_instance.yml"

- name: Get git diff
  ansible.builtin.command:
    cmd: "git diff"
    chdir: "{{ instance_path }}/config"
  register: _git_diff
  changed_when: false

- name: Display diff
  ansible.builtin.debug:
    msg: "{{ _git_diff.stdout | default('No changes.') }}"
