---
# canasta config get - Show configuration settings.
# Input: id (optional), keys (str: space-separated keys), force (bool)

- name: Resolve instance
  ansible.builtin.include_tasks: >-
    {{ canasta_root }}/roles/common/tasks/resolve_instance.yml

- name: Get specified keys
  when: keys is defined and keys | length > 0
  ansible.builtin.include_tasks: _get_single.yml
  loop: "{{ keys.split() }}"
  loop_control:
    loop_var: _config_get_key

- name: Get all settings
  when: keys is not defined or keys | length == 0
  block:
    - name: Read all settings
      canasta_env:
        path: "{{ instance_path }}/.env"
        state: read_all
      register: _config_all

    - name: Display all settings (sorted)
      ansible.builtin.debug:
        msg: |-
          {% for item in _config_all.variables
             | dict2items
             | sort(attribute='key') %}
          {{ item.key }}={{ item.value }}
          {% endfor %}
