---
# canasta extension enable - Enable extensions.

- name: Enable extensions
  ansible.builtin.include_role:
    name: extensions_skins
    tasks_from: enable.yml
  vars:
    _item_type: extensions
    _names: "{{ extensions }}"
