---
# canasta extension list - List installed extensions.

- name: List extensions
  ansible.builtin.include_role:
    name: extensions_skins
    tasks_from: list.yml
  vars:
    _item_type: extensions
    _item_dir: extensions
