---
# canasta skin enable - Enable skins.

- name: Enable skins
  ansible.builtin.include_role:
    name: extensions_skins
    tasks_from: enable.yml
  vars:
    _item_type: skins
    _names: "{{ skins }}"
