---
# canasta skin disable - Disable skins.

- name: Disable skins
  ansible.builtin.include_role:
    name: extensions_skins
    tasks_from: disable.yml
  vars:
    _item_type: skins
    _names: "{{ skins }}"
