{{- if .Values.configData.caddy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canasta.fullname" . }}-caddy-config
  namespace: {{ include "canasta.namespace" . }}
  labels:
    {{- include "canasta.labels" . | nindent 4 }}
    app.kubernetes.io/component: caddy
data:
  {{- range $key, $value := .Values.configData.caddy }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
