apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canasta.fullname" . }}-db-config
  namespace: {{ include "canasta.namespace" . }}
  labels:
    {{- include "canasta.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
data:
  {{- if .Values.configData.db }}
  {{- range $key, $value := .Values.configData.db }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
  {{- else }}
  my.cnf: |
    {{- .Files.Get "files/my.cnf" | nindent 4 }}
  {{- end }}
