apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canasta.fullname" . }}-varnish-config
  namespace: {{ include "canasta.namespace" . }}
  labels:
    {{- include "canasta.labels" . | nindent 4 }}
    app.kubernetes.io/component: varnish
data:
  {{- range $key, $value := .Values.configData.varnish }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
